### ISSUE TITLE
pwmexplorer in C?

### ISSUE THREAD

**Issue by jlpoolen** [youngkin/gpio#1]
The documentation at https://youngkin.github.io/post/pulsewidthmodulationraspberrypi/#exploring-pwm-on-a-raspberry-pi states:

`PWM Explorer supports C and Go. Choosing C you can experiment with both Mark/Space and Balanced PWM Modes. The Go library I used, go-rpio[6](https://youngkin.github.io/post/pulsewidthmodulationraspberrypi/#fn:6) only supports Mark/Space.`

I am finding "go" code, but not a lot of "c" code that might relate to the PWM Explorer, a screenshot of which is at https://youngkin.github.io/images/pwmfordummies/pwmexplorer.jpg:

jlpoole@pizero2 /usr/local/src/gpio $ find . -type f -name "*.c"
./ledbargraph/ledbargraph.c
./ledblink/bcmfuncs.c
./ledblink/blinkingled.c
./ledblink/blinkinglednolib.c
./ledblink/matrixlednolib.c
./ledmatrixspi/leddotmatrix.c
./ledmatrixspi/leddotmatrixnolib.c
./ledmatrixspi/spidev_test.c
./pwmdemo/pwmexplorer/apps/freqtest.c
./rgbled/resetrgb.c
./rgbled/rgbled.c
./rgbled/rgbledHardware.c
./sevensegdisplay/sevensegdisplay.c
jlpoole@pizero2 /usr/local/src/gpio $

Where would I find the "c" code for the PWM Explorer?

**Comment by youngkin** [comment]
The PWM Explorer application is written in Go. However, it has the ability to run both Go and C code to control PWM functions on a Raspberry Pi. See ./pwmdemo/pwmexplorer/apps/freqtest.c for the associated C module invoked by PEM Explorer.
